### ISSUE TITLE
Pourquoi l'exemple de CSV utilise-t-il des ";" comme séparateur de champ ?

### ISSUE THREAD

**Issue by fconil** [etalab/schema-indice-reparabilite#5]
bonjour,
CSV signifiant comma separated value, pourquoi ne pas utiliser la virgule par défaut comme le décrit la [rfc4180](https://datatracker.ietf.org/doc/html/rfc4180) .
Utiliser la virgule évite d'avoir à indiquer aux différents outils que le séparateur est ";" au lieu de ",".
Merci

**Comment by Pierlou** [comment]
Bonjour, les séparateurs "," et ";" sont indifféremment pris en compte par nos outils de validation. Vous êtes libre de créer des fichiers avec la virgule comme séparateur, ils sont également acceptés.
